import json
import os
from pathlib import Path

from google import genai
from google.genai import types, errors


BASE_DIR = Path(__file__).resolve().parent
FINDINGS_PATH = BASE_DIR / "findings.json"
SAMPLE_OUTPUT_PATH = BASE_DIR / "sample_output.txt"


# Load verified findings generated by Part 2.
with open(FINDINGS_PATH, "r", encoding="utf-8") as f:
    findings_from_json = json.load(f)

print("Findings loaded successfully.")


def generate_scr_narrative(findings: dict) -> dict:
    """Generate the SCR narrative using Gemini when a key is available."""
    key = os.environ.get("GEMINI_API_KEY")

    if not key:
        return {
            "status": "error",
            "narrative": None,
            "message": "GEMINI_API_KEY is not set."
        }

    client = genai.Client(api_key=key)

    system_instruction = """
    You are a senior data analyst writing for Mamaearth's
    regional ops and finance heads.

    Write the business narrative using exactly three labeled sections:

    Situation
    Complication
    Resolution

    Every number in the output must come only from the supplied findings
    and must appear with the same value.

    IMPORTANT:
    The narrative MUST explicitly include all of these verified figures:

    1. cleaned total revenue
    2. COD return rate
    3. highest-risk COD + Tier-2 return rate
    4. duplicate reconciliation delta
    5. true peak month and its revenue

    Do not omit any of these figures.

    Do not invent statistics, percentages, revenue figures, dates,
    or other numerical facts.Only make business claims that are directly supported by the
    supplied findings. Do not infer or claim revenue growth,
    profitability impact, margin erosion, causation, trends such as
    "surged", or operational impact unless those facts are explicitly
    present in the findings.
    """

    user_prompt = f"""
    Create an SCR business narrative using these verified findings:

    {findings}

    Explain the situation, the key complication revealed by
    the data, and the resolution/action implied by the findings.
    """

    try:
        response = client.models.generate_content(
            model="gemini-3.1-flash-lite",
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.0,
                max_output_tokens=500,
                http_options=types.HttpOptions(timeout=15000)
            )
        )

        return {
            "status": "success",
            "narrative": response.text.strip(),
            "tokens": response.usage_metadata.total_token_count
        }

    except errors.APIError as e:
        return {"status": "error", "narrative": None, "message": str(e)}
    except Exception as e:
        return {"status": "error", "narrative": None, "message": str(e)}


def generate_scr_narrative_offline(findings: dict) -> dict:
    """Generate a deterministic SCR narrative without Gemini or internet."""
    cleaned_revenue = findings["cleaned_total_revenue_inr"]
    raw_revenue = findings["raw_total_revenue_inr"]
    delta = findings["duplicate_reconciliation_delta_inr"]

    cod_rate = findings["return_rate_by_payment"]["COD"]

    risk_payment = findings["highest_risk_segment"]["payment_method"]
    risk_tier = findings["highest_risk_segment"]["city_tier"]
    risk_rate = findings["highest_risk_segment"]["return_rate_pct"]

    peak_month = findings["true_peak_month"]["month"]
    peak_revenue = findings["true_peak_month"]["revenue_inr"]

    inflated_month = findings["outlier_inflated_month"]["month"]
    apparent_revenue = findings["outlier_inflated_month"]["apparent_revenue_inr"]
    corrected_revenue = findings["outlier_inflated_month"]["corrected_revenue_inr"]

    narrative = f"""
Situation

The raw total revenue was {raw_revenue:.2f} INR.
After reconciliation, the cleaned total revenue was
{cleaned_revenue:.2f} INR. The reconciliation delta was
{delta:.2f} INR. The true peak month was {peak_month},
with revenue of {peak_revenue:.2f} INR.

Complication

The {inflated_month} revenue initially appeared to be
{apparent_revenue:.2f} INR, but the corrected revenue was
{corrected_revenue:.2f} INR after accounting for the identified
outliers. Payment-method analysis also showed a COD return rate
of {cod_rate:.1f}%. The highest-risk segment was
{risk_payment} with Tier-{risk_tier} cities, where the return
rate was {risk_rate:.1f}%.

Resolution

Use the cleaned revenue of {cleaned_revenue:.2f} INR as the
verified revenue baseline. Focus operational attention on the
{risk_payment} and Tier-{risk_tier} segment with its
{risk_rate:.1f}% return rate, and use the outlier-corrected
monthly figures when evaluating performance. The true peak
month remains {peak_month}, with revenue of {peak_revenue:.2f} INR.
""".strip()

    return {"status": "success", "narrative": narrative, "tokens": 0}


def check_narrative_numbers(narrative: str) -> bool:
    """Check the five required verified figures."""
    normalized = narrative.replace(",", "")

    checks = {
        "Cleaned revenue (97358.30)": (
            "97358.30" in normalized or "97358.3" in normalized
        ),
        "COD return rate (44.4)": "44.4" in normalized,
        "COD + Tier-2 return rate (54.5)": "54.5" in normalized,
        "Duplicate reconciliation delta (2501.90)": (
            "2501.90" in normalized
            or "2501.9" in normalized
            or "2501.899999" in normalized
        ),
        "March peak revenue (March + 20318.90)": (
            ("March" in narrative or "2026-03" in narrative)
            and ("20318.90" in normalized or "20318.9" in normalized)
        )
    }

    all_passed = True
    print("=" * 60)
    print("TASK 5 — Numeric Accuracy Checklist")
    print("=" * 60)

    for check_name, passed in checks.items():
        if passed:
            print(f"PASS ✓ — {check_name}")
        else:
            print(f"FAIL ✗ — {check_name}")
            all_passed = False

    print("=" * 60)
    print("Overall Result: PASS ✓" if all_passed else "Overall Result: FAIL ✗")
    return all_passed


# Try Gemini first; automatically use the offline fallback if needed.
result = generate_scr_narrative(findings_from_json)

if result["status"] == "error":
    print("Gemini failed. Switching to offline fallback.")
    result = generate_scr_narrative_offline(findings_from_json)

print("Final Status:", result["status"])
print("\nNarrative:\n")
print(result["narrative"])

# Verify the required figures.
check_narrative_numbers(result["narrative"])

# Save the generated narrative.
with open(SAMPLE_OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(result["narrative"])

print("\nsample_output.txt created successfully.")

# Verify the saved output too.
with open(SAMPLE_OUTPUT_PATH, "r", encoding="utf-8") as f:
    saved_output = f.read()

check_narrative_numbers(saved_output)
